### ISSUE TITLE
Possible to add POOL_COIN and POOL_ALGO?

### ISSUE THREAD

**Issue by WesNz** [metal3d/docker-xmrig#1]
Hi

this works for xmrig great...
but trying to add other coins and have no idea how to add the "algo" and "coin" option.

is there an easy/nasty hack that i can do to make it work?

**Comment by metal3d** [comment]
Mmmmh let me try tomorrow, nice idea

**Comment by WesNz** [comment]
awesome! miner works good in docker

**Comment by WesNz** [comment]
any luck with algo and coin features?
i know the commands for xmrig but not sure how to convert it to data thats in entrypoint

**Comment by metal3d** [comment]
I'm working on, sorry, I was very busy last days

**Comment by metal3d** [comment]
Docker is building the version, you will have access to 5.1.0-2 tag (or latest) and you will be able to pass:

- `COIN`
- `ALGO`

As environment variable, of course :)

Tell me if it's ok for you. I will close the issue if you confirm.

Thanks a lot for the feature request ;)

**Comment by metal3d** [comment]
Version are building on Docker Hub, please wait a bit, take a look on the docker page: https://hub.docker.com/r/metal3d/xmrig and wait the latest build to appear.

**Comment by WesNz** [comment]
sup man!

Thats Awesome!
Will give it a go today

**Comment by metal3d** [comment]
I don't have any answer, I close the issue. If you have other question or something goes wrong, feel free to open a new issue ;)
