### ISSUE TITLE
MSR kernel module is not available

### ISSUE THREAD

**Issue by c0dyhi11** [metal3d/docker-xmrig#4]
```
[2022-01-11 03:14:08.182]  msr      msr kernel module is not available
[2022-01-11 03:14:08.182]  msr      FAILED TO APPLY MSR MOD, HASHRATE WILL BE LOW
```
Is this something that you've experienced? Or have gotten a work around for?
This reduces hashrate by a lot compared to running xmrig outside a container. 

```
$ docker --version
Docker version 20.10.9, build c2ea9bc
```

**Comment by metal3d** [comment]
I have this warning too. I will recompile a new version in a few days. Sorry for the delay, some problems to resolve outside this project ;)

**Comment by thibp** [comment]
How about this issue? Thanks

**Comment by metal3d** [comment]
Sorry, too busy for a moment, I will take a look in a few hours/days (baby is born, hard to find some times)

**Comment by dankthropod** [comment]
I'm sorry to disturb, but I'm still having this issue. Are you planning on maintaining this?

**Comment by metal3d** [comment]
I'm sorry, I had a lot of stuffs to do.
I'm currently checking what happend to my proxy and I will update the image / Dockerfile

**Comment by metal3d** [comment]
I finally found why it doesn't set MSR.

I give explanation in the README file. You need to set some devices, use privileged container and sudo (to make it possible to touch host CPU MSR)

Can you try, and reopen the issue if it doesn't work for you ?
