### ISSUE TITLE
TLS support?

### ISSUE THREAD

**Issue by LordKillZone** [metal3d/docker-xmrig#7]
How i can add TLS fingerprint? I am using docker compose, tried to add -tls and -tls-fingerprint=(value) but it dont work.

**Comment by metal3d** [comment]
Sorry for the delay...

I never tried this option, can you give me some details, or a documentation page? I'll add this option if possible.

**Comment by Badbird5907** [comment]
For anyone who comes across this, pass the env variable OTHERS_OPTS, for example `docker run ... -e OTHERS_OPTS="--tls" ...`

**Comment by metal3d** [comment]
As @Badbird5907  says, the option works. I close the issue with a very long delay and all my apologies.
