### ISSUE TITLE
Update to v6.20.0

### ISSUE THREAD

**Issue by hundehausen** [metal3d/docker-xmrig#8]
Hello @metal3d ,

could you please make a new release with the [latest xmrig version](https://github.com/xmrig/xmrig/releases/tag/v6.20.0)?

Thank you!

**Comment by metal3d** [comment]
I'll try in a few hours. Sorry for late answers.

Le jeu. 21 sept. 2023, 09:27, hundehausen ***@***.***> a
écrit :

**Comment by metal3d** [comment]
Done, sorry for the delay.

It's now using Ubuntu (I don't like but that's the only possibility to propose CUDA computing).
